add_newline = false

format = """$directory$git_branch$git_status$status$character"""

# move the rest of the prompt to the right
# right_format = """$status$git_branch$git_status"""
# right_format = """"""

[character]
success_symbol = "[❯](purple)[❯](cyan)"
error_symbol = "[❯](yellow)[❯](red)"
vicmd_symbol = "[❮](purple)[❮](cyan)"

[python]
disabled = true
format = '[(\($virtualenv\) )]($style)'
style = 'white'

[directory]
style = "blue"
truncation_length = 1
truncation_symbol = ""
fish_style_pwd_dir_length = 1

# right prompt uses left space padding
[git_branch]
format = '[$branch]($style)'
style = 'green'

[git_status]
format = '( [$ahead_behind$stashed]($style)) '
style = "cyan"
stashed = "≡"
ahead = "⇡${count}"
behind = "⇣${count}"

# [custom.git_status_dirty]
# when = 'test -n "$(git status --porcelain 2>/dev/null)"'
# symbol = "•"
# style = "white"
# format="[$symbol]($style)"
# shell = ["sh"]

[cmd_duration]
format = ' [$duration]($style)'

[line_break]
disabled = true

[status]
disabled = false
symbol = ' ✘'
